HotelPanel/Controllers/AccommodationController.cs
using Common;
using Constants;
using Logic.BusinessObjects;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Data.ViewModel.AccommodationModels;
using PagedList;

namespace HotelPanel.Controllers
{
    public class AccommodationController : BaseController
    {

        AccommodationBusiness _AccommodationBusiness = new AccommodationBusiness();

        [HttpGet]
        public JsonResult GetCountries(string query)
        {
            try
            {
                return Json(new { success = true, data = _AccommodationBusiness.GetCountries(query) }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

                return Json(new { success = false, message = ex.Message });
            }
        }

        [HttpGet]
        public JsonResult GetCities(string query)
        {
            try
            {
                return Json(new { success = true, data = _AccommodationBusiness.GetCities(query) }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

                return Json(new { success = false, message = ex.Message });
            }
        }

        // GET: Accommodation
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult List(bool showVerified = false, bool onlyVerified = false, int page = 1, int pageSize = 20)
        {
            ViewBag.ShowVerified = showVerified;
            ViewBag.OnlyVerified = onlyVerified;
            ViewBag.PageSize = pageSize;
            ViewBag.Restricted = true;
            return View(_AccommodationBusiness.GetAccommodationByUser(CurrentUser.UserID, showVerified, onlyVerified)?.ToPagedList(page, pageSize));
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult List(SearchAccommodation Model, int page = 1, int pageSize = 20)
        {
            ViewBag.Restricted = false;
            if (ModelState.IsValid)
                return View(_AccommodationBusiness.GetNames(Model)?.ToPagedList(page, pageSize));
            return View();
        }
        public ActionResult Images(long AccommodationID)
        {
            var Images = _AccommodationBusiness.GetImages(AccommodationID);
            FilterImagesView Model = new FilterImagesView
            {
                AccommodationID = AccommodationID,
                AccomodationImages = Images
            };
            return View(Model);
        }
        public ActionResult RoomImages(long id)
        {
            try
            {
                var result = new GroupRoomImage();
                result.AccommodationId = id;
                result.RoomImages = _AccommodationBusiness.GetGroupedRoomImage(id);
                return View(result);
            }
            catch (Exception)
            {

                throw;
            }
        }

        public ActionResult Weather(string AccommodationID)
        {
            long Entry = AccommodationID.IsNormalized() ? long.Parse(AccommodationID) : 0;
            var Model = _AccommodationBusiness.GetWeather(Entry);
            return View(Model);
        }
        [HttpPost]
        public JsonResult Filter(FilterImagesView model)
        {
            try
            {
                if (model != null)
                {
                    var result = _AccommodationBusiness.VerifyAccommodationImages(CurrentUser.UserID, model);
                    if (result)
                    {
                        return Json(new { success = true }, JsonRequestBehavior.AllowGet);
                    }
                    return Json(new { success = false, message = "Verify Accommodation Images failed." }, JsonRequestBehavior.AllowGet);
                }
                return Json(new { success = false, message = "Model is invalid." }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {

                throw;
            }
        }
        public ActionResult Facility(long AccommodationID)
        {
            AccommodationFacility Model = new AccommodationFacility();
            var Facility = _AccommodationBusiness.GetFacilities(AccommodationID);
            var Description = _AccommodationBusiness.GetDescription(AccommodationID);
            string Name = _AccommodationBusiness.GetAccommodation(AccommodationID).Name;
            Model.Facilities = new List<Data.DataModel.Facility>(Facility);
            Model.Description = Description;
            Model.AccommodationID = AccommodationID;
            Model.Name = Name;
            return View(Model);
        }
        public ActionResult EditName(long id)
        {
            var accommodation = _AccommodationBusiness.GetAccommodation(id);
            EditName Model = new EditName
            {
                AccommodationID = accommodation.AccommodationlID,
                Name = accommodation.Name
            };
            return View(Model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditName(EditName Model)
        {
            if (ModelState.IsValid)
            {
                var Result = _AccommodationBusiness.EditName(Model);
                iUserStorage.Store(PublicConstants.Session.Message_Success, PublicConstants.Message.Success);
                return View(Model);
            }
            iUserStorage.Store(PublicConstants.Session.Message_Error, PublicConstants.Message.Faild);
            return View(Model);
        }
        public ActionResult EditDescription(long id)
        {
            var accommodation = _AccommodationBusiness.GetAccommodation(id);
            EditDescription Model = new EditDescription
            {
                AccommodationID = accommodation.AccommodationlID,
                Description = accommodation.Description
            };
            return View(Model);
        }
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult EditDescription(EditDescription Model)
        {
            if (ModelState.IsValid)
            {
                var Result = _AccommodationBusiness.EditDescription(Model);
                iUserStorage.Store(PublicConstants.Session.Message_Success, PublicConstants.Message.Success);
                return View(Model);
            }
            iUserStorage.Store(PublicConstants.Session.Message_Error, PublicConstants.Message.Faild);
            return View(Model);
        }
        public ActionResult ListFacility(long id)
        {
            var Facilities = _AccommodationBusiness.GetFacilities();
            var accommodation = _AccommodationBusiness.GetAccommodation(id);
            ListFacilities Model = new ListFacilities
            {
                AccommodationID = accommodation.AccommodationlID,
                AccommodationName = accommodation.Name,
                Facilities = Facilities
            };
            return View(Model);
        }
        public ActionResult AddFacility()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddFacility(AddFacilities Model)
        {
            if (ModelState.IsValid)
            {
                var Result = _AccommodationBusiness.AddFacilities(Model);
                iUserStorage.Store(PublicConstants.Session.Message_Success, PublicConstants.Message.Success);
                return View();
            }
            iUserStorage.Store(PublicConstants.Session.Message_Error, PublicConstants.Message.Faild);
            return View();
        }
        public ActionResult EditFacility(long id)
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditFacility(EditFacilities Model)
        {
            if (ModelState.IsValid)
            {
                var Result = _AccommodationBusiness.EditFacilities(Model);
                iUserStorage.Store(PublicConstants.Session.Message_Success, PublicConstants.Message.Success);
                return View(Result);
            }
            iUserStorage.Store(PublicConstants.Session.Message_Error, PublicConstants.Message.Faild);
            return View();
        }
        public ActionResult ListLanguageDescription(long AccommodationID)
        {
            Data.ViewModel.AccommodationModels.ListLanguageDescription Model = new Data.ViewModel.AccommodationModels.ListLanguageDescription()
            {
                AccommodationID = AccommodationID,
                AccommodationDescriptions = _AccommodationBusiness.ListOtherLanguageDescription(AccommodationID)
            };
            return View(Model);
        }
        public ActionResult AddDescription(long AccommodationID)
        {
            var enumDataType = from Common.Language e in Language.GetValues(typeof(Language)) select new { ID = (int)e, Name = e.ToString() };
            ViewBag.LanguageID = new SelectList(enumDataType, "ID", "Name");
            return View(new Data.ViewModel.AccommodationModels.AddDescriptionViewModel() { AccommodationID = AccommodationID });
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult AddDescription(AddDescription Model)
        {
            if (ModelState.IsValid)
            {
                var Result = _AccommodationBusiness.AddDescription(Model);
                if (Result)
                {
                    iUserStorage.Store(PublicConstants.Session.Message_Success, PublicConstants.Message.Success);
                    return RedirectToAction("ListLanguageDescription", new { AccommodationID = Model.AccommodationID });
                }
                else
                {
                    iUserStorage.Store(PublicConstants.Session.Message_Error, PublicConstants.Message.Faild);

HotelPanel/Views/Accommodation/AddDescription.cshtml
@model Data.ViewModel.AccommodationModels.AddDescriptionViewModel
<script type="text/javascript" src="~/Content/Scripts/jquery.js"></script>
<!-- Include Editor style. -->
<link href='https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.8.4/css/froala_editor.min.css' rel='stylesheet' type='text/css' />
<link href='https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.8.4/css/froala_style.min.css' rel='stylesheet' type='text/css' />

<!-- Include JS file. -->
<script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.8.4/js/froala_editor.min.js'></script>

<div class="bgc-white p-20 bd">
    <h6 class="c-grey-900">Edit Accommodation Name</h6>
    <div class="mT-30">
        @using (Html.BeginForm("AddDescription", "Accommodation", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(x => x.AccommodationID)
        <div class="form-group">
            <label for="LanguageID">Accommodation Description</label>
            @Html.DropDownList("LanguageID", ViewBag.EnumList as SelectList, new { @class = "form-control", @id = "LanguageID" })
            <label for="exampleInputEmail1">Accommodation Description</label>
            @Html.TextAreaFor(x => x.Description, new { @rows = "10", id = "froala-editor" })
        </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        }
    </div>
</div>
<script>
    $(function () {
        $('textarea#froala-editor').froalaEditor();
    });
</script>

HotelPanel/Views/Accommodation/AddFacility.cshtml
@{
    /**/

    string Message_Alert = Common.iUserStorage.Retrive<string>(Constants.PublicConstants.Session.Message_Error);
    string Message_Success = Common.iUserStorage.Retrive<string>(Constants.PublicConstants.Session.Message_Success);
}
@if (!String.IsNullOrEmpty(Message_Alert))
{
    <div class="alert alert-danger" role="alert">@Message_Alert</div>
    Common.iUserStorage.Remove(Constants.PublicConstants.Session.Message_Error);
}
@if (!String.IsNullOrEmpty(Message_Success))
{
    <div class="alert alert-success" role="alert">@Message_Success</div>
    Common.iUserStorage.Remove(Constants.PublicConstants.Session.Message_Success);
}

HotelPanel/Views/Accommodation/ChangeDescription.cshtml
@model Data.ViewModel.AccommodationModels.EditDescriptionViewModel
<script type="text/javascript" src="~/Content/Scripts/jquery.js"></script>
<!-- Include Editor style. -->
<link href='https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.8.4/css/froala_editor.min.css' rel='stylesheet' type='text/css' />
<link href='https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.8.4/css/froala_style.min.css' rel='stylesheet' type='text/css' />

<!-- Include JS file. -->
<script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.8.4/js/froala_editor.min.js'></script>

<div class="bgc-white p-20 bd">
    <h6 class="c-grey-900">Edit Accommodation Name</h6>
    <div class="mT-30">
        @using (Html.BeginForm("ChangeDescription", "Accommodation", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(x => x.AccommodationID)
            @Html.HiddenFor(x => x.AccommodationDescriptionID)
            <div class="form-group">
                <label for="LanguageID">Accommodation Description</label>
                @Html.DropDownList("LanguageID", ViewBag.EnumList as SelectList, new { @class = "form-control", @id = "LanguageID" })
                <label for="exampleInputEmail1">Accommodation Description</label>
                @Html.TextAreaFor(x => x.Description, new { @rows = "10", id = "froala-editor" })
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        }
    </div>
</div>
<script>
    $(function () {
        $('textarea#froala-editor').froalaEditor();
    });
</script>

HotelPanel/Views/Accommodation/EditDescription.cshtml
@model Data.ViewModel.AccommodationModels.EditDescription
@{
    /**/

    string Message_Alert = Common.iUserStorage.Retrive<string>(Constants.PublicConstants.Session.Message_Error);
    string Message_Success = Common.iUserStorage.Retrive<string>(Constants.PublicConstants.Session.Message_Success);
}
@if (!String.IsNullOrEmpty(Message_Alert))
{
    <div class="alert alert-danger" role="alert">@Message_Alert</div>
    Common.iUserStorage.Remove(Constants.PublicConstants.Session.Message_Error);
}
@if (!String.IsNullOrEmpty(Message_Success))
{
    <div class="alert alert-success" role="alert">@Message_Success</div>
    Common.iUserStorage.Remove(Constants.PublicConstants.Session.Message_Success);
}
<script type="text/javascript" src="~/Content/Scripts/jquery.js"></script>
<!-- Include Editor style. -->
<link href='https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.8.4/css/froala_editor.min.css' rel='stylesheet' type='text/css' />
<link href='https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.8.4/css/froala_style.min.css' rel='stylesheet' type='text/css' />

<!-- Include JS file. -->
<script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.8.4/js/froala_editor.min.js'></script>

<div class="bgc-white p-20 bd">
    <h6 class="c-grey-900">Edit Accommodation Name</h6>
    <div class="mT-30">
        @using (Html.BeginForm("EditDescription", "Accommodation", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(x => x.AccommodationID)
            <div class="form-group">
                <label for="exampleInputEmail1">Accommodation Description</label>
                @Html.TextAreaFor(x => x.Description, new { @rows = "10", id = "froala-editor" })
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        }
    </div>
</div>
<script>
    $(function () {
        $('textarea#froala-editor').froalaEditor()
    });
</script>

HotelPanel/Views/Accommodation/EditFacility.cshtml
@model Data.ViewModel.AccommodationModels.EditName
@{

}

<div class="bgc-white p-20 bd">
    <h6 class="c-grey-900">Edit Accommodation Name</h6>
    <div class="mT-30">
        @using (Html.BeginForm("EditName", "Accommodation", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <div class="form-group">
                <label for="exampleInputEmail1">Accommodation Name</label>
                <input type="text" class="form-control" placeholder="Enter Name" name="Name">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        }
    </div>
</div>

HotelPanel/Views/Accommodation/Facility.cshtml
@model Data.ViewModel.AccommodationModels.AccommodationFacility
@{
    /**/

    string Message_Alert = Common.iUserStorage.Retrive<string>(Constants.PublicConstants.Session.Message_Error);
    string Message_Success = Common.iUserStorage.Retrive<string>(Constants.PublicConstants.Session.Message_Success);
}
@if (!String.IsNullOrEmpty(Message_Alert))
{
    <div class="alert alert-danger" role="alert">@Message_Alert</div>
    Common.iUserStorage.Remove(Constants.PublicConstants.Session.Message_Error);
}
@if (!String.IsNullOrEmpty(Message_Success))
{
    <div class="alert alert-success" role="alert">@Message_Success</div>
    Common.iUserStorage.Remove(Constants.PublicConstants.Session.Message_Success);
}
<div class="bdT pX-40 pY-30">
    <h4>Accommodation Name @Html.ActionLink("Edit", "EditName", new { id = Model.AccommodationID }, new { @class = "btn cur-p btn-warning" })</h4>

    <p>
        @Model.Name
    </p>
    <h4>Description @Html.ActionLink("Edit", "EditDescription", new { id = Model.AccommodationID }, new { @class = "btn cur-p btn-warning" })  @Html.ActionLink("Other Language", "ListLanguageDescription", new { AccommodationID = Model.AccommodationID }, new { @class = "btn cur-p btn-warning" })</h4>
    <p>
        @Html.Raw(Model.Description)
    </p>
    <h4>Facilities @Html.ActionLink("Add", "ListFacility", new { id = Model.AccommodationID }, new { @class = "btn cur-p btn-success" })</h4> <small>Hover the mouse over the facility name to display the edit button</small>
    @foreach (var item in Model.Facilities)
    {
        <p>
            @Html.ActionLink("Edit", "EditFacility", new { id = item.FacilityID }, new { @class = "btn cur-p btn-warning" }) @item.Name
        </p>
    }

</div>

HotelPanel/Views/Accommodation/_Table.cshtml
@{
    string twenty = null;
    string fifty = null;
    string hundred = null;
    string numFirstDis = null;
    string numPreDis = null;
    string numNextDis = null;
    string numLastDis = null;
    switch (ViewBag.PageSize)
    {
        case 20:
            twenty = "selected";
            break;
        case 50:
            fifty = "selected";
            break;
        case 100:
            hundred = "selected";
            break;
        default:
            twenty = "selected";
            break;
    }
    if (Model.IsFirstPage)
    {
        numFirstDis = "disabled";
        numPreDis = "disabled";
    }
    if (Model.IsLastPage)
    {
        numLastDis = "disabled";
        numNextDis = "disabled";
    }
}
<link href="~/Content/datatables.min.css" rel="stylesheet" />
<div class="row">
    <div class="col-md-12">
        <div class="bgc-white bd bdrs-3 p-20 mB-20">
            <h4 class="c-grey-900 mB-20">Accommodation List</h4>
            <div>
                <button class="btn btn-info submit_btn" data-action="/Accommodation/MultipleAccommodationImage" disabled>Accommodation Images</button>
                <button class="btn btn-info submit_btn" data-action="/Accommodation/MultipleRoomsImages" disabled>Room Images</button>
            </div>

            @if (ViewBag.Restricted)
            {
                object check = ViewBag.ShowVerified ? "checked" : null;
                object onlyVerifiedCheck = ViewBag.OnlyVerified ? "checked" : null;
                <div class="checkbox checkbox-circle checkbox-info peers ai-c mB-15">
                    <input type="checkbox" id="inputCall1" name="Verified" class="peer" @check>
                    <label for="inputCall1" class="peers peer-greed js-sb ai-c"><span class="peer peer-greed">Show Verified Accommodations</span></label>
                </div>
                <div class="checkbox checkbox-circle checkbox-info peers ai-c mB-15">
                    <input type="checkbox" id="inputCall2" name="Verified" class="peer" @onlyVerifiedCheck>
                    <label for="inputCall2" class="peers peer-greed js-sb ai-c"><span class="peer peer-greed">Only Show Verified Accommodations</span></label>
                </div>
            }
            <div class="accomodation_paging">
                <span class="text-item">
                    Show
                    <select class="page_number form-control">
                        <option @twenty>20</option>
                        <option @fifty>50</option>
                        <option @hundred>100</option>
                    </select>
                    items
                </span>
                <button class="btn cur-p btn-primary numFirst leftArrow" @numFirstDis><<</button>
                <button class="btn cur-p btn-primary numPre leftArrow" @numPreDis><</button>
                <span class="title-page">page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount</span>
                <button class="btn cur-p btn-primary numNext rightArrow" @numNextDis>></button>
                <button class="btn cur-p btn-primary numLast rightArrow" @numLastDis>>></button>
                <span class="search_input">
                    <input type="text" id="searchInput" placeholder="Search..." class="form-control"/>
                </span>
            </div>
            <form method="post" target="_blank">
                <table id="datatable" class="table table-striped table-bordered" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th class="no-sort"><input type="checkbox" class="checkAll" /></th>
                            <th>Accommodation ID</th>
                            <th>Name</th>
                            <th>City</th>
                            <th>Country</th>
                            <th>Last Update</th>
                            <th class="no-sort">Options</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th><input type="checkbox" class="checkAll" /></th>
                            <th>Accommodation ID</th>
                            <th>Name</th>
                            <th>City</th>
                            <th>Country</th>
                            <th>Last Update Date</th>
                            <th>Options</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach (var Item in Model)
                        {
                            <tr>
                                <td><input type="checkbox" name="accommodationsID" value="@Item.AccommodationID" /></td>
                                <td>@Item.AccommodationID</td>
                                <td>@Item.Name</td>
                                <td>@Item.CityName</td>
                                <td>@Item.Country</td>
                                <td>@Item.lastUpdate</td>
                                <td>
                                    @*<a href="Images/?AccommodationID=@Item.AccommodationID" class="btn cur-p btn-secondary">Images</a>*@
                                    <a href="Weather/?AccommodationID=@Item.AccommodationID" class="btn cur-p btn-primary">Weather</a>
                                    <a href="Facility/?AccommodationID=@Item.AccommodationID" class="btn cur-p btn-warning">Facility</a>
                                    <a target="_blank" href="~/VerifyPanel/Details/@Item.AccommodationID" class="btn cur-p btn-info">Verify</a>
                            </tr>
                        }
                    </tbody>
                </table>
            </form>
            <div class="accomodation_paging">
                <span class="text-item">
                    Show
                    <select class="page_number form-control">
                        <option @twenty>20</option>
                        <option @fifty>50</option>
                        <option @hundred>100</option>
                    </select>
                    items
                </span>
                <button class="btn cur-p btn-primary numFirst leftArrow" @numFirstDis><<</button>
                <button class="btn cur-p btn-primary numPre leftArrow" @numPreDis><</button>
                <span class="title-page">page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount</span>
                <button class="btn cur-p btn-primary numNext rightArrow" @numNextDis>></button>
                <button class="btn cur-p btn-primary numLast rightArrow" @numLastDis>>></button>
                <span class="search_input">
                    <input type="text" id="searchInput" placeholder="Search..." class="form-control" />
                </span>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="~/Scripts/datatables.min.js"></script>
<script>
    $(document).ready(function () {
        $("#searchInput").on("keyup", function () {
            var value = $(this).val().toLowerCase();
            $("#datatable tr").filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
        //$('#datatable').DataTable({
        //    "order": [],
        //    "columnDefs": [{ "orderable": false, "targets": 0 },{
        //        "targets": 'no-sort',
        //        "orderable": false,
        //    }],
        //});
    });
    $(".checkAll").change(function () {
        if ($(this).is(":checked")) {
            $(".checkAll").prop("checked", true);
            $("input[name=accommodationsID]").prop("checked", true).trigger("change");
        } else {
            $(".checkAll").prop("checked", false);
            $("input[name=accommodationsID]").prop("checked", false).trigger("change");
        }
    })
    $("#inputCall1").change(function () {
        var checked = $(this).is(":checked");
        window.location.href = '/Accommodation/List?showVerified=' + checked;
    })
    $("#inputCall2").change(function () {
        var checked = $(this).is(":checked");
        window.location.href = '/Accommodation/List?onlyVerified=' + checked;
    })
    $("input[name=accommodationsID]").change(function () {
        var checked = false;
        if (!$(this).is(":checked")) {
            $(".checkAll").prop("checked", false);
        }
        $("input[name=accommodationsID]").each(function () {
            if ($(this).is(":checked")) {
                checked = true;
                return false;
            }
        })
        if (checked) {
            $(".submit_btn").prop("disabled", false);
        } else {
            $(".submit_btn").prop("disabled", true);
        }
    })
    $(".submit_btn").click(function () {
        var action = $(this).data("action");
        $("form").attr("action", action);
        $("form").submit();
    })
    $(".numFirst").click(function () {
        window.location.href = '@Html.Raw(Url.Action("List", "Accommodation", new { showVerified = ViewBag.ShowVerified, onlyVerified = ViewBag.OnlyVerified, page = 1, pageSize = ViewBag.PageSize }))';
    });
    $(".numPre").click(function () {
        window.location.href = '@Html.Raw(Url.Action("List", "Accommodation", new { showVerified = ViewBag.ShowVerified, onlyVerified = ViewBag.OnlyVerified, page = Model.PageNumber == 1 ? Model.PageNumber : Model.PageNumber - 1, pageSize = ViewBag.PageSize}))';
    });
    $(".numNext").click(function () {
        window.location.href = '@Html.Raw(Url.Action("List", "Accommodation", new { showVerified = ViewBag.ShowVerified, onlyVerified = ViewBag.OnlyVerified, page = Model.PageNumber == Model.PageCount ? Model.PageNumber : Model.PageNumber + 1, pageSize = ViewBag.PageSize}))';
    });
    $(".numLast").click(function () {
        window.location.href = '@Html.Raw(Url.Action("List", "Accommodation", new { showVerified = ViewBag.ShowVerified, onlyVerified = ViewBag.OnlyVerified, page = Model.PageCount, pageSize = ViewBag.PageSize}))';
    });
    $(".page_number").change(function () {
        var a = $(this).val();
        window.location.href = '/Accommodation/List?showVerified=@ViewBag.ShowVerified&onlyVerified=@ViewBag.OnlyVerified' + '&page=1' + '&pageSize=' + a;
    });
    $(".search_name").on("keyup", function () {
        var value = $(this).val();

        $("#datatable tr").each(function (index) {
            if (index !== 0) {

                $row = $(this);

                var id = $row.find("td:eq(2)").text();

                if (id.indexOf(value) !== 0) {
                    $row.hide();
                }
                else {
                    $row.show();
                }
            }
        });
    });
</script>